services:

  wordpress:
    container_name: wp-1  
    image: wordpress:latest
    restart: "unless-stopped"
    ports:
      - "8200:80"
    volumes:
      - ./wordpress:/var/www/html  
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress

  db:
    container_name: mysql-1  
    image: mariadb:latest
    restart: "unless-stopped"
    volumes:
      - ./db:/var/lib/mysql        
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: '1'

  phpmyadmin: 
    container_name: phpmyadmin-1     
    depends_on:      
    - db    
    image: phpmyadmin/phpmyadmin:latest    
    links:      
    - db    
    ports:      
    - "8080:80"    
    restart: "unless-stopped"
    
  cli:
    container_name: cli-1 
    image: wordpress:cli
    volumes:
      - ./wordpress:/var/www/html  


